export const GET_ERROR = "GET_ERROR";

export const GET_PROJECTS = "GET_PROJECTS";

export const GET_PROJECT = "GET_PROJECT";

export const DELETE_PROJECT = "DELETE_PROJECT";


export const GET_BACKLOG = "GET_BACKLOG";

export const GET_PROJECTS_TASKS= "GET_PROJECTS_TASKS";

export const DELETE_PROJECT_TASKS = "DELETE_PROJECT_TASKS";